name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Prebuild the project
        run: npx expo prebuild

      - name: Build APK
        run: ./gradlew assembleRelease --build-cache

      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: android/app/build/outputs/apk/release/*.apk
