name: Build EAS APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install --save-dev eas-cli
        
      - name: Build APK
        run: npx eas build --platform android --non-interactive

      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v4

        with:
          name: EAS-APK
          path: build/*
